title: è²“è™çš®ã®éƒ¨è½æ ¼
owner: è²“è™çš®
description: ä¸€éš»å°è²“æ¯›éæ•çš„è²“
language: zh-TW
timeZone: +0800
timeFormat: '%Y/%m/%d'
siteUrl: https://maohupi.github.io

twitter:
  site: '@jhou5846'
  creator: '@jhou5846'
liker:
  account: jhou5846

iconPath: 
  ico: image/configImage/icon.ico
  png: image/configImage/icon.png

avatarPath: image/configImage/avatar.png

badges:
  - icon: ğŸ›ï¸
    message: ç·¨æ›²ã€æ··éŸ³
  - icon: ğŸ’»
    message: è»Ÿé«”ã€ç¶²é ç·¨å¯«
  - icon: âœ¨
    message: åœ–åƒç‰¹æ•ˆè£½ä½œ

tabs:
  home:
    text: é¦–é 
  about:
    text: é—œæ–¼
    path: about.md
  articles:
    text: æ–‡ç« 
  portfolio:
    text: ä½œå“
tabsAmount: 4

switches:
  rssUrl:
    text: è¤‡è£½RSS
  backgroundMusic:
    text: èƒŒæ™¯éŸ³æ¨‚
    path: audio/ä¼‘_å¥”.wav
    volume: 0.5
  darkMode:
    text: æ·±è‰²å¸ƒæ™¯
switchesAmount: 3

pages: 
  filter:
    text: Filter
    archives: Archives
    categories: Categories
    tags: Tags
  outline:
    text: Outline

category:
  - name: scripting
    color:
      bright: '#c5d7c1'
      dark: '#608857'
  - name: tools
    color:
      bright: '#c0cdd8'
      dark: '#55738b'
  - name: tips
    color:
      bright: '#d6ccc2'
      dark: '#846d58'

skinPath: image/configImage/maohupi_mcskin.png